use_frameworks!

platform :ios, '8.0'

target 'VVCustomNavigationBar_Example' do
  pod 'VVCustomNavigationBar', :path => '../'

  target 'VVCustomNavigationBar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
